id: I6590FF86
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-15 07:17:58.937897+00:00
last_modified: 2022-12-15 07:17:58.937903+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-072-025
  eft-text-version: 1.1.2 2020
  title: Toh_325-The_Verses_of_Naga_King_Drum-v2
bases:
  CC80:
    source_metadata: null
    order: 1
    base_file: CC80.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
